// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals all --version 5

// Make sure that with or without `-fsplit-cold-code` that the trap blocks don't
// get outlined into their own function. Outlining trap blocks is unhelpful
// because it makes debugging harder which is the opposite of what
// `-fbounds-safety-unique-trap` is tries to do.

// RUN: %clang_cc1 -O2 -triple arm64e-apple-ios -fbounds-safety \
// RUN:   -fno-bounds-safety-unique-traps -emit-llvm %s -o - -fno-split-cold-code \
// RUN: | FileCheck %s
// RUN: %clang_cc1 -O2 -triple arm64e-apple-ios -fbounds-safety \
// RUN:   -fno-bounds-safety-unique-traps -emit-llvm %s -o - -fsplit-cold-code \
// RUN: | FileCheck %s
#include <ptrcheck.h>

#define __bs_unique_traps __attribute__((unique_traps("bounds-safety")))

// Should have 1 trap
// CHECK-LABEL: define i32 @i_want_to_be_inlined(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8:![0-9]+]]
// CHECK-NEXT:    [[OR_COND3:%.*]] = select i1 [[OR_COND]], i1 [[TMP3]], i1 false, !prof [[PROF9:![0-9]+]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[OR_COND3]], label %[[CONT2:.*]], label %[[TRAP:.*]], !prof [[PROF9]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation [[META10:![0-9]+]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP4]]
//
__attribute__((always_inline)) int i_want_to_be_inlined(
  int* __bidi_indexable ptr, int idx) {
    return ptr[idx];
}

// FIXME: Should have 1 trap but currently has 2. It seems after inlining the
// traps aren't being merged despite not having the `nomerge` attribute
// (rdar://160872194).
// CHECK-LABEL: define i32 @consume(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], ptr dead_on_return noundef readonly captures(none) [[PTR2:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR2]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 16
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[IDXPROM_I:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr i32, ptr [[BYVAL_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX_I]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[BYVAL_TEMP_SROA_4_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX_I]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP1]], [[TMP2]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX_I]], [[BYVAL_TEMP_SROA_5_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    [[OR_COND3_I:%.*]] = select i1 [[OR_COND_I]], i1 [[TMP3]], i1 false, !prof [[PROF9]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[OR_COND3_I]], label %[[I_WANT_TO_BE_INLINED_EXIT:.*]], label %[[TRAP_I:.*]], !prof [[PROF9]], !annotation [[META7]]
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[I_WANT_TO_BE_INLINED_EXIT]]:
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[TMP4]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP4]], !annotation [[META7]]
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP5]], [[TMP6]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP7:%.*]] = icmp uge ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    [[OR_COND3:%.*]] = select i1 [[OR_COND]], i1 [[TMP7]], i1 false, !prof [[PROF9]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[OR_COND3]], label %[[CONT2:.*]], label %[[TRAP:.*]], !prof [[PROF9]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    ret i32 [[TMP8]]
//
int consume(int* __bidi_indexable ptr, int* __bidi_indexable ptr2, int idx) {
  int other = i_want_to_be_inlined(ptr2, idx);
  return ptr[idx];
}

// Should have 3 traps
// CHECK-LABEL: define i32 @i_want_to_be_inlined_unmerged(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !prof [[PROF13:![0-9]+]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[DOTNOT5:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT5]], label %[[TRAP1:.*]], label %[[CONT2:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP1]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[DOTNOT6:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[DOTNOT6]], label %[[TRAP3:.*]], label %[[CONT4:.*]], !prof [[PROF13]], !annotation [[META8]]
// CHECK:       [[TRAP3]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[CONT4]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
__attribute__((always_inline)) int i_want_to_be_inlined_unmerged(
  int* __bidi_indexable ptr, int idx) __bs_unique_traps {
    return ptr[idx];
}

// Should have 6 (3+3) traps
// CHECK-LABEL: define i32 @consume_unmerged(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], ptr dead_on_return noundef readonly captures(none) [[PTR2:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR2]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 16
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[IDXPROM_I:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr i32, ptr [[BYVAL_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX_I]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[DOTNOT_I:%.*]] = icmp ugt ptr [[TMP0]], [[BYVAL_TEMP_SROA_4_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT_I]], label %[[TRAP_I:.*]], label %[[CONT_I:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT_I]]:
// CHECK-NEXT:    [[DOTNOT5_I:%.*]] = icmp ugt ptr [[ARRAYIDX_I]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT5_I]], label %[[TRAP1_I:.*]], label %[[CONT2_I:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP1_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT2_I]]:
// CHECK-NEXT:    [[DOTNOT6_I:%.*]] = icmp ult ptr [[ARRAYIDX_I]], [[BYVAL_TEMP_SROA_5_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[DOTNOT6_I]], label %[[TRAP3_I:.*]], label %[[I_WANT_TO_BE_INLINED_UNMERGED_EXIT:.*]], !prof [[PROF13]], !annotation [[META8]]
// CHECK:       [[TRAP3_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[I_WANT_TO_BE_INLINED_UNMERGED_EXIT]]:
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP1]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[DOTNOT6:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT6]], label %[[TRAP1:.*]], label %[[CONT2:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP1]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[DOTNOT7:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[DOTNOT7]], label %[[TRAP3:.*]], label %[[CONT4:.*]], !prof [[PROF13]], !annotation [[META8]]
// CHECK:       [[TRAP3]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[CONT4]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    ret i32 [[TMP2]]
//
int consume_unmerged(int* __bidi_indexable ptr, int* __bidi_indexable ptr2, int idx) __bs_unique_traps {
  int other = i_want_to_be_inlined_unmerged(ptr2, idx);
  return ptr[idx];
}

// Should 4 (3 + 1) traps
// CHECK-LABEL: define i32 @consume_partially_unmerged(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], ptr dead_on_return noundef readonly captures(none) [[PTR2:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR2]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 16
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[IDXPROM_I:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr i32, ptr [[BYVAL_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX_I]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[BYVAL_TEMP_SROA_4_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX_I]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP1]], [[TMP2]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX_I]], [[BYVAL_TEMP_SROA_5_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    [[OR_COND3_I:%.*]] = select i1 [[OR_COND_I]], i1 [[TMP3]], i1 false, !prof [[PROF9]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[OR_COND3_I]], label %[[I_WANT_TO_BE_INLINED_EXIT:.*]], label %[[TRAP_I:.*]], !prof [[PROF9]], !annotation [[META7]]
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[I_WANT_TO_BE_INLINED_EXIT]]:
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt ptr [[TMP4]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT]], label %[[TRAP:.*]], label %[[CONT:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT]]:
// CHECK-NEXT:    [[DOTNOT6:%.*]] = icmp ugt ptr [[ARRAYIDX]], [[TMP4]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT6]], label %[[TRAP1:.*]], label %[[CONT2:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP1]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[DOTNOT7:%.*]] = icmp ult ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[DOTNOT7]], label %[[TRAP3:.*]], label %[[CONT4:.*]], !prof [[PROF13]], !annotation [[META8]]
// CHECK:       [[TRAP3]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[CONT4]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    ret i32 [[TMP5]]
//
int consume_partially_unmerged(int* __bidi_indexable ptr, int* __bidi_indexable ptr2, int idx) __bs_unique_traps {
  // The inlined function doesn't have `__bs_unique_traps` but this function does.
  int other = i_want_to_be_inlined(ptr2, idx);
  return ptr[idx];
}

// This function should have 4 (3+1) traps
// CHECK-LABEL: define i32 @consume_partially_unmerged2(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[PTR:%.*]], ptr dead_on_return noundef readonly captures(none) [[PTR2:%.*]], i32 noundef [[IDX:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR2]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_4_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_4_0_PTR2_SROA_IDX]], align 8
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR2]], i64 16
// CHECK-NEXT:    [[BYVAL_TEMP_SROA_5_0_COPYLOAD:%.*]] = load ptr, ptr [[BYVAL_TEMP_SROA_5_0_PTR2_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[IDXPROM_I:%.*]] = sext i32 [[IDX]] to i64
// CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr i32, ptr [[BYVAL_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARRAYIDX_I]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[DOTNOT_I:%.*]] = icmp ugt ptr [[TMP0]], [[BYVAL_TEMP_SROA_4_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT_I]], label %[[TRAP_I:.*]], label %[[CONT_I:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT_I]]:
// CHECK-NEXT:    [[DOTNOT5_I:%.*]] = icmp ugt ptr [[ARRAYIDX_I]], [[TMP0]], !annotation [[META7]]
// CHECK-NEXT:    br i1 [[DOTNOT5_I]], label %[[TRAP1_I:.*]], label %[[CONT2_I:.*]], !prof [[PROF13]], !annotation [[META7]]
// CHECK:       [[TRAP1_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META7]]
// CHECK-NEXT:    unreachable, !annotation [[META7]]
// CHECK:       [[CONT2_I]]:
// CHECK-NEXT:    [[DOTNOT6_I:%.*]] = icmp ult ptr [[ARRAYIDX_I]], [[BYVAL_TEMP_SROA_5_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[DOTNOT6_I]], label %[[TRAP3_I:.*]], label %[[I_WANT_TO_BE_INLINED_UNMERGED_EXIT:.*]], !prof [[PROF13]], !annotation [[META8]]
// CHECK:       [[TRAP3_I]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4]], !annotation [[META8]]
// CHECK-NEXT:    unreachable, !annotation [[META8]]
// CHECK:       [[I_WANT_TO_BE_INLINED_UNMERGED_EXIT]]:
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[PTR]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_PTR_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_PTR_SROA_IDX]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 [[IDXPROM_I]]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[ARRAYIDX]], i64 4, !annotation [[META7]]
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[TMP1]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP3:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP1]], !annotation [[META7]]
// CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP2]], [[TMP3]], !annotation [[META7]]
// CHECK-NEXT:    [[TMP4:%.*]] = icmp uge ptr [[ARRAYIDX]], [[AGG_TEMP_SROA_3_0_COPYLOAD]], !annotation [[META8]]
// CHECK-NEXT:    [[OR_COND3:%.*]] = select i1 [[OR_COND]], i1 [[TMP4]], i1 false, !prof [[PROF9]], !annotation [[META8]]
// CHECK-NEXT:    br i1 [[OR_COND3]], label %[[CONT2:.*]], label %[[TRAP:.*]], !prof [[PROF9]], !annotation [[META7]]
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation [[META10]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       [[CONT2]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA11]]
// CHECK-NEXT:    ret i32 [[TMP5]]
//
int consume_partially_unmerged2(int* __bidi_indexable ptr, int* __bidi_indexable ptr2, int idx)  {
  // The inlined function has `__bs_unique_traps` but this function doesn't
  int other = i_want_to_be_inlined_unmerged(ptr2, idx);
  return ptr[idx];
}


//.
// CHECK: attributes #[[ATTR0]] = { alwaysinline nounwind memory(read, inaccessiblemem: write) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// CHECK: attributes #[[ATTR1:[0-9]+]] = { cold noreturn nounwind memory(inaccessiblemem: write) }
// CHECK: attributes #[[ATTR2]] = { nounwind memory(read, inaccessiblemem: write) "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
// CHECK: attributes #[[ATTR3]] = { noreturn nounwind }
// CHECK: attributes #[[ATTR4]] = { nomerge noreturn nounwind }
//.
// CHECK: [[META0:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
// CHECK: [[META1:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"p1 int", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"any pointer", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// CHECK: [[META6]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[META7]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// CHECK: [[META8]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[PROF9]] = !{!"branch_weights", i32 -12288, i32 12286}
// CHECK: [[META10]] = !{!"bounds-safety-check-ptr-le-upper-bound", !"bounds-safety-check-ptr-ge-lower-bound"}
// CHECK: [[TBAA11]] = !{[[META12:![0-9]+]], [[META12]], i64 0}
// CHECK: [[META12]] = !{!"int", [[META5]], i64 0}
// CHECK: [[PROF13]] = !{!"branch_weights", i32 1, i32 1048575}
//.
